#!/bin/sh

# put this script somewhere like $HOME/bin or /usr/local/bin

# set this to your paste bucket
URL='http://pasteb.herokuapp.com'

# if curl is in some odd place, set this accordinly
$CURL='curl'

# use it like this:
# $ cat bin/pasteb | pasteb 
#     http://pasteb.herokuapp.com/1
$CURL -F 'paste=<-' $URL
